<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Proyecto-Spotify</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="proyecto-spotify_files/libs/clipboard/clipboard.min.js"></script>
<script src="proyecto-spotify_files/libs/quarto-html/quarto.js"></script>
<script src="proyecto-spotify_files/libs/quarto-html/popper.min.js"></script>
<script src="proyecto-spotify_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="proyecto-spotify_files/libs/quarto-html/anchor.min.js"></script>
<link href="proyecto-spotify_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="proyecto-spotify_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="proyecto-spotify_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="proyecto-spotify_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="proyecto-spotify_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proyecto-Spotify</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="preferencia-musical-de-los-estudiantes-universitarios-de-lima-según-datos-de-spotify" class="level1">
<h1>Preferencia musical de los estudiantes universitarios de Lima según datos de Spotify</h1>
<p>Proyecto realizado para el curso de Estadística y Probabilidades II: <span class="citation" data-cites="Utec">@Utec</span></p>
<section id="relevancia" class="level2">
<h2 class="anchored" data-anchor-id="relevancia">Relevancia</h2>
<ul>
<li><p><strong>Aplicaciones de datos en IA:</strong> El uso de Inteligencia Artificial (IA) en Spotify incluye el reconocimiento de emociones en canciones, lo que sirve para mejorar listas de reproducción personalizadas y la experiencia general del usuario. Al analizar elementos como el tono, el tempo y la letra de una canción, Spotify puede determinar el estado de ánimo que transmite y sugerir música que se alinee con las emociones o el estado mental del usuario. Por ejemplo, si un usuario tiende a escuchar canciones tranquilas y melódicas por la noche, Spotify puede identificar esta tendencia y recomendar canciones similares durante ese momento del día. Además, Spotify utiliza algoritmos de aprendizaje automático en su sistema de recomendación. Estos algoritmos consideran factores como la popularidad de la canción, las tendencias musicales actuales y lo que están escuchando los usuarios con gustos similares. Esto permite a Spotify ofrecer recomendaciones altamente personalizadas.</p></li>
<li><p><strong>Aplicaciones de datos en marketing:</strong> ¿Cómo contribuye el análisis estadístico de datos musicales al marketing actual? La música es parte de la vida diaria de las personas y las empresas están interesadas en satisfacer las necesidades principales de sus usuarios. Considerando a Spotify como una de las aplicaciones de música más conocidas hoy en día, la recolección de sus datos presenta una fuente interesante de información para el marketing de la empresa, especialmente porque son datos públicos. Las empresas a menudo utilizan datos de Spotify para centrarse en analizar los comportamientos y preferencias de los usuarios con el fin de crear estrategias más efectivas. Esto podría incluir segmentación de audiencia y personalización de mensajes publicitarios, colaboraciones con músicos populares (o en tendencia), o análisis probabilístico tanto de tendencias actuales como futuras.</p></li>
</ul>
</section>
<section id="objetivos" class="level2">
<h2 class="anchored" data-anchor-id="objetivos">Objetivos</h2>
<p>Este es un estudio que recopila datos de múltiples estudiantes universitarios de Lima con el objetivo de encontrar patrones en sus preferencias musicales. Realizaremos casos de estudio donde investigaremos</p>
<ul class="task-list">
<li><input type="checkbox">Estudio de la variable ‘danceability’, variable cuantitativa continua que mide qué tan bailable es una canción.</li>
<li><input type="checkbox">Relación entre la ‘danceability’ y la edad.
<ul>
<li>Hipótesis: La ‘danceability’ promedio de las canciones escuchadas es mayor al 50% en personas entre las edades de 15 y 25 años.</li>
</ul></li>
<li><input type="checkbox">¿Cómo ha evolucionado la intensidad promedio de</li>
</ul>
</section>
<section id="obtención-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="obtención-de-datos">Obtención de datos</h2>
<p>Cada entrada en el conjunto de datos corresponderá al ID de usuario de un estudiante y tendrá como valor una lista de artistas que escuchan, el número de veces que los escuchan, entre otros. Los datos se obtendrán de la API de Spotify, con el siguiente código (simplificado):</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Authorize and Authenticate</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ...</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotipy <span class="im">import</span> Spoify</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>top_artists: Const <span class="op">=</span> spotify.current_user_top_artists()</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>top_tracks: Const <span class="op">=</span> spotify.current_user_top_tracks()</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>listened_artists: Spotify.Artist[] <span class="op">=</span> []</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Extra data</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> track <span class="kw">in</span> top_tracks[<span class="st">"items"</span>]:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    features <span class="op">=</span> spotify.audio_features(track[<span class="st">"id"</span>])</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    analysis <span class="op">=</span> spotify.audio_analysis(track[<span class="st">"id"</span>])</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    listened_artists.merge(track[<span class="st">"artists"</span>][<span class="st">'items'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Para obtener los IDs de usuario y los datos, necesitaremos crear un sistema de autenticación que nos permita obtener los datos de las personas. Además, tendremos un canal de datos que extraerá información relevante de la API de Spotify y la almacenará en Google Sheets, que luego se podrá exportar a un CSV y finalmente a un dataframe de R.</p>
</section>
<section id="integrantes" class="level2">
<h2 class="anchored" data-anchor-id="integrantes">Integrantes</h2>
<table class="table">
<tbody>
<tr class="odd">
<td><img src="https://avatars.githubusercontent.com/u/104233007?v=4.png" class="img-fluid" alt="Arturo Magno"><br>
<a href="https://github.com/xkal1bur">Arturo Magno</a></td>
<td><img src="https://avatars.githubusercontent.com/u/91209653?v=4.png" class="img-fluid" alt="Valentin Quezada"><br>
<a href="https://github.com/ValentinQuezada">Valentin Quezada</a></td>
<td><img src="https://avatars.githubusercontent.com/u/60308719?v=4.png" class="img-fluid" alt="Enrique Flores"><br>
<a href="https://github.com/Enriquefft">Enrique Flores</a></td>
</tr>
</tbody>
</table>
</section>
<section id="variables-utilizadas-en-el-estudio" class="level2">
<h2 class="anchored" data-anchor-id="variables-utilizadas-en-el-estudio">Variables utilizadas en el estudio</h2>
<p>Este estudio requiere que los usuarios proporcionen sus datos de Spotify, lo cual podría ser un problema para algunas personas. Necesitaremos asegurarnos de que los datos estén anonimizados y que los usuarios estén al tanto de qué datos estamos recopilando y cómo los estamos utilizando. Teniendo todo esto en cuenta, esperamos que una aplicación web atractiva nos ayude a obtener una buena cantidad de datos. En cuanto al público objetivo, esperamos obtener una buena cantidad de datos de los estudiantes de UTEC, así como de otras universidades en Lima, especialmente si consideramos que casi todos los estudiantes universitarios utilizan Spotify.</p>
<p>La cantidad mínima de datos que necesitamos son 200 entradas, pero para un estudio más robusto, necesitaríamos al menos 500 entradas. En el peor de los casos, los datos serán principalmente de UTEC, lo que generará sesgo en el primer objetivo. No obstante, intearemos recopilar la mayor cantidad de data posible, variada en su mayoría.</p>
<section id="variables-primarias" class="level4">
<h4 class="anchored" data-anchor-id="variables-primarias">Variables primarias</h4>
<table class="table">
<colgroup>
<col style="width: 27%">
<col style="width: 20%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Tipo</th>
<th>Restricciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Centro de estudio</td>
<td>Nominal categórica</td>
<td>Ninguna</td>
</tr>
<tr class="even">
<td>Edad</td>
<td>Cuantitativa discreta</td>
<td>~ [15, 40]</td>
</tr>
<tr class="odd">
<td>Distrito</td>
<td>Nominal categórica</td>
<td>Distritos de Lima, Perú</td>
</tr>
<tr class="even">
<td>Variedad musical percibida</td>
<td>Nominal ordinal</td>
<td>{Ninguna (1), Baja (2), Media (3), Alta (4), Muy alta (5)}</td>
</tr>
<tr class="odd">
<td>Géneros preferidos percibidos</td>
<td>Nominal categórica</td>
<td>Géneros musicales de Spotify</td>
</tr>
</tbody>
</table>
</section>
<section id="variables-secundarias" class="level4">
<h4 class="anchored" data-anchor-id="variables-secundarias">Variables secundarias</h4>
<table class="table">
<colgroup>
<col style="width: 60%">
<col style="width: 20%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Tipo</th>
<th>Restricciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>‘Danceability’ promedio de canciones favoritas</td>
<td>Numérica continua</td>
<td>[0, 1]</td>
</tr>
<tr class="even">
<td>Característica acústica promedio de canciones favoritas</td>
<td>Numérica continua</td>
<td>[0, 1]</td>
</tr>
<tr class="odd">
<td>Nivel de energía promedio de canciones favoritas</td>
<td>Numérica continua</td>
<td>[0, 1]</td>
</tr>
<tr class="even">
<td>Intensidad de volumen promedio de canciones favoritas</td>
<td>Numérica continua</td>
<td>[-60, 0] DB</td>
</tr>
<tr class="odd">
<td>Artistas escuchados por año</td>
<td>Numérica continua</td>
<td><span class="math inline">\(\mathbb{R}^+\)</span></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>librerias <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"dplyr"</span>, <span class="st">"ggplot2"</span>, <span class="st">"reshape2"</span>, <span class="st">"readr"</span>, <span class="st">"randtests"</span>, <span class="st">"tidyverse"</span>, <span class="st">"lmtest"</span>, <span class="st">"purrr"</span>, <span class="st">"nortest"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (paquete <span class="cf">in</span> librerias) {</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(paquete, <span class="at">character.only =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">install.packages</span>(paquete, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">library</span>(paquete, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"spotify_data.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 260 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): favourite_gender, spotify_id, percieved_variety, study_center, dist...
dbl (6): average_danceability, average_energy, average_loudness, average_aco...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(DF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  favourite_gender average_danceability average_energy average_loudness
  &lt;chr&gt;                           &lt;dbl&gt;          &lt;dbl&gt;            &lt;dbl&gt;
1 rock                            0.682          0.401           -10.1 
2 rock                            0.303          0.88             -4.74
3 r&amp;b                             0.845          0.652            -7.50
4 r&amp;b                             0.425          0.378            -5.82
5 pop                             0.76           0.887            -1.99
6 r&amp;b                             0.496          0.639            -6.16
# ℹ 7 more variables: average_acousticness &lt;dbl&gt;, spotify_id &lt;chr&gt;, age &lt;dbl&gt;,
#   percieved_variety &lt;chr&gt;, listened_artists &lt;dbl&gt;, study_center &lt;chr&gt;,
#   distrito &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>variable_name <span class="ot">&lt;-</span> <span class="fu">names</span>(DF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="caso-de-estudio-1" class="level1">
<h1>Caso de Estudio #1</h1>
<section id="distribución-de-la-media-muestral-de-danceability-para-los-encuestados-entre-15-a-18-años." class="level2">
<h2 class="anchored" data-anchor-id="distribución-de-la-media-muestral-de-danceability-para-los-encuestados-entre-15-a-18-años.">Distribución de la media muestral de ‘danceability’ para los encuestados entre 15 a 18 años.</h2>
<p>El objetivo del primer caso de estudio es evaluar la variable ‘danceability’ en encuestados entre las edades de 15 y 18 años. Tenemos como dato la media de la población, <span class="math inline">\(\mu\)</span>, que podemos calcular usando RStudio. Luego, filtramos la base de datos para los encuestados que tienen entre 15 y 18 años. Esta será nuestra muestra, y entonces buscamos su tamaño (n) y la desviación muestral (s).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">=</span> <span class="fu">mean</span>(DF<span class="sc">$</span>average_danceability)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>DFD <span class="ot">&lt;-</span> <span class="fu">filter</span>(DF,age <span class="sc">&gt;=</span> <span class="dv">15</span> <span class="sc">&amp;</span> age <span class="sc">&lt;=</span> <span class="dv">18</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">complete.cases</span>(DFD))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">=</span> <span class="fu">sd</span>(DFD<span class="sc">$</span>average_danceability)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"mu ="</span>, mu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "mu = 0.664669230769231"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"n ="</span>, n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "n = 79"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"s ="</span>, s)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "s = 0.146037375225229"</code></pre>
</div>
</div>
<p>Entendemos para este caso que, como el tamaño de muestra es menor a 30, la media muestral se distribuye con una T-student de <span class="math inline">\(n-1\)</span> grados de libertad. Con esta información, podemos ahora resolver los siguientes incisos:</p>
<section id="a.-cuál-es-la-probabilidad-de-que-la-media-muestral-sea-mayor-a-0.65" class="level4">
<h4 class="anchored" data-anchor-id="a.-cuál-es-la-probabilidad-de-que-la-media-muestral-sea-mayor-a-0.65">a. ¿Cuál es la probabilidad de que la media muestral sea mayor a 0.65?</h4>
<p><span class="math display">\[P(\overline{x}&gt;0.65)\]</span></p>
<p><span class="math display">\[P\left(\frac{\overline{x}-\mu}{\frac{s}{\sqrt{n}}} &gt; \frac{0.65-\mu}{\frac{s}{\sqrt{n}}}\right)\]</span></p>
<p><span class="math display">\[P\left(T(n-1)&gt;\frac{0.65-\mu}{\frac{s}{\sqrt{n}}}\right)\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> (<span class="fl">0.65</span> <span class="sc">-</span> mu)<span class="sc">/</span>(s<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"La probabilidad de que la media muestral sea mayor a 0.65 es"</span>, <span class="fu">pt</span>(a,n<span class="dv">-1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>),<span class="st">"."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La probabilidad de que la media muestral sea mayor a 0.65 es 0.812646209374997 ."</code></pre>
</div>
</div>
</section>
<section id="b.-será-posible-determinar-un-intervalo-de-confianza-para-la-media-muestral-consideremos-un-nivel-de-confianza-del-95." class="level4">
<h4 class="anchored" data-anchor-id="b.-será-posible-determinar-un-intervalo-de-confianza-para-la-media-muestral-consideremos-un-nivel-de-confianza-del-95.">b. ¿Será posible determinar un intervalo de confianza para la media muestral? Consideremos un nivel de confianza del 95%.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>nc <span class="ot">=</span> <span class="fl">0.95</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> nc</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(DFD<span class="sc">$</span>average_danceability, <span class="at">conf.level =</span> nc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"El intervalo de confianza para la media poblacional es ["</span>, test<span class="sc">$</span>conf.int[<span class="dv">1</span>], <span class="st">";"</span>, test<span class="sc">$</span>conf.int[<span class="dv">2</span>], <span class="st">"] con un nivel de confianza del 95%."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El intervalo de confianza para la media poblacional es [ 0.651859030593054 ; 0.717280209913276 ] con un nivel de confianza del 95%."</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>Xs <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Xs, <span class="fu">dt</span>(Xs,n<span class="dv">-1</span>), <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(Xs[Xs <span class="sc">&gt;</span> a], <span class="fu">dt</span>(Xs[Xs <span class="sc">&gt;</span> a],n<span class="dv">-1</span>), <span class="at">col =</span> <span class="st">"green"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">c</span>(<span class="sc">-</span>test<span class="sc">$</span>conf.int[<span class="dv">1</span>], test<span class="sc">$</span>conf.int[<span class="dv">2</span>]), <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"T(x,n-1)"</span>, <span class="st">"respuesta de la a."</span>, <span class="st">"respuesta de la b."</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>,<span class="st">"blue"</span>), <span class="at">lty =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="proyecto-spotify_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="caso-de-estudio-2" class="level1">
<h1>Caso de estudio #2</h1>
<section id="distribución-de-la-varianza-muestral-de-la-variedad-musical-de-los-encuestados." class="level2">
<h2 class="anchored" data-anchor-id="distribución-de-la-varianza-muestral-de-la-variedad-musical-de-los-encuestados.">Distribución de la varianza muestral de la variedad musical de los encuestados.</h2>
<p>El objetivo del segundo caso de estudio es evaluar la variable ‘perceived_variety’. No obstante, nos falta como dato la varianza de la población, <span class="math inline">\(\sigma^2\)</span>, para poder trabajar el caso. Nuestra base de datos entera servirá en este caso como muestra, y al ser de un tamaño mayor a 30, podemos aproximar la varianza muestral a la varianza poblacional. El principal objetivo será entonces calcular la varianza poblacional usando RStudio, pero para ello, primero debemos refactorizar la data nominal a numérica:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>numeric_variety <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">factor</span>(DF<span class="sc">$</span>percieved_variety))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">=</span> <span class="fu">var</span>(numeric_variety)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">complete.cases</span>(DF))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"v ="</span>, v)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "v = 2.18644193644194"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"n ="</span>, n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "n = 260"</code></pre>
</div>
</div>
<section id="a.-cuál-sería-la-máxima-varianza-muestral-con-probabilidad-0.90" class="level4">
<h4 class="anchored" data-anchor-id="a.-cuál-sería-la-máxima-varianza-muestral-con-probabilidad-0.90">a. ¿Cuál sería la máxima varianza muestral con probabilidad 0.90?</h4>
<p><span class="math display">\[
P(s^2\leq m) = 0.90
\]</span></p>
<p><span class="math display">\[
P\left(\frac{s^2(n-1)}{\sigma^2}\leq\frac{m(n-1)}{\sigma^2}\right)=0.90
\]</span></p>
<p><span class="math display">\[
P\left(\chi^2_{(n-1)}\leq\frac{m(n-1)}{\sigma^2}\right)=0.90
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">=</span> <span class="fu">qchisq</span>(<span class="fl">0.90</span>,n<span class="dv">-1</span>) <span class="sc">*</span> v <span class="sc">/</span> (n<span class="dv">-1</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"La máxima varianza muestral con probabilidad 0.90 es"</span>, m,<span class="st">"."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La máxima varianza muestral con probabilidad 0.90 es 2.43600258577709 ."</code></pre>
</div>
</div>
</section>
<section id="b.-será-posible-determinar-un-intervalo-de-confianza-para-la-varianza-poblacional-consideremos-un-nivel-de-confianza-del-95." class="level4">
<h4 class="anchored" data-anchor-id="b.-será-posible-determinar-un-intervalo-de-confianza-para-la-varianza-poblacional-consideremos-un-nivel-de-confianza-del-95.">b. ¿Será posible determinar un intervalo de confianza para la varianza poblacional? Consideremos un nivel de confianza del 95%.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>nc <span class="ot">=</span> <span class="fl">0.95</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> nc</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>superior <span class="ot">=</span> (n<span class="dv">-1</span>) <span class="sc">*</span> v <span class="sc">/</span> <span class="fu">qchisq</span>(alpha<span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>inferior <span class="ot">=</span> (n<span class="dv">-1</span>) <span class="sc">*</span> v <span class="sc">/</span> <span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"El intervalo de confianza para la varianza poblacional es ["</span>, inferior, <span class="st">";"</span>, superior, <span class="st">"]."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El intervalo de confianza para la varianza poblacional es [ 1.85382009831019 ; 2.61788319596268 ]."</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="caso-de-estudio-3" class="level1">
<h1>Caso de estudio #3</h1>
<p>Distribución de la diferencia de medias de la intensidad de la música escuchada por los encuestados de edad mayor a 20 años y la intensidad de la música escuchada por los encuestados de edad menor a 20 años.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age <span class="sc">&lt;=</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(average_loudness) <span class="ot">-&gt;</span> df1</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age <span class="sc">&gt;</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(average_loudness) <span class="ot">-&gt;</span> df2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetros</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>mu1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(df1<span class="sc">$</span>average_loudness)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>mu2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(df2<span class="sc">$</span>average_loudness)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> <span class="fu">sd</span>(df1<span class="sc">$</span>average_loudness)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> <span class="fu">sd</span>(df2<span class="sc">$</span>average_loudness)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="fu">length</span>(df1<span class="sc">$</span>average_loudness)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="fu">length</span>(df2<span class="sc">$</span>average_loudness)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"mu1 ="</span>, mu1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "mu1 = -6.43416853932584"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"mu2 ="</span>, mu2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "mu2 = -7.57893902439024"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"s1 ="</span>, s1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "s1 = 2.80439262480004"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"s2 ="</span>, s2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "s2 = 3.38753398542493"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"n1 ="</span>, n1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "n1 = 178"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"n2 ="</span>, n2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "n2 = 82"</code></pre>
</div>
</div>
<p>¿Cual es la distribución de la diferencia de medias?</p>
<p>Calculamos si la varianza es igual o diferente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(df1<span class="sc">$</span>average_loudness, df2<span class="sc">$</span>average_loudness, <span class="at">ratio =</span> <span class="dv">1</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  df1$average_loudness and df2$average_loudness
F = 0.68535, num df = 177, denom df = 81, p-value = 0.04006
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.4653713 0.9830978
sample estimates:
ratio of variances 
         0.6853467 </code></pre>
</div>
</div>
<p>Vemos que las varianzas son diferentes.</p>
<p>Estamos en el caso de: no se conoce <span class="math inline">\(\sigma_1\)</span> y <span class="math inline">\(\sigma\_2\)</span> pero se sabe que son diferentes.</p>
<p>$$ <span class="math display">\[\begin{align*}
&amp; T(v) = \frac{\overline{X}_1 - \overline{X}_2 - (\mu_1 - \mu_2)} {\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}} \,,\text{ siendo} \\

v &amp;= \frac{\left(\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}\right)^2} {\frac{\left(\frac{s_1^2}{n_1}\right)^2}{n_1 - 1} + \frac{\left(\frac{s_2^2}{n_2}\right)^2}{n_2 - 1}} = \text{grados de libertad}
\end{align*}\]</span> $$</p>
<p>Valores importantes</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> mu1 <span class="sc">-</span> mu2 </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((s1<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n1) <span class="sc">+</span> (s2<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n2)) </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">round</span>( (s1<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n1 <span class="sc">+</span> s2<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n2)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>((s1<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n1)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(n1<span class="dv">-1</span>) <span class="sc">+</span> (s2<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n2)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(n2<span class="dv">-1</span>))  )</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>,v)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="a.-cuál-es-la-probabilidad-de-que-en-promedio-la-intensidad-de-la-música-escuchada-por-los-encuestados-menores-a-18-años-supere-en-10-decibeles-a-la-intensidad-de-la-música-escuchada-por-los-encuestados-mayores-a-22-años" class="level4">
<h4 class="anchored" data-anchor-id="a.-cuál-es-la-probabilidad-de-que-en-promedio-la-intensidad-de-la-música-escuchada-por-los-encuestados-menores-a-18-años-supere-en-10-decibeles-a-la-intensidad-de-la-música-escuchada-por-los-encuestados-mayores-a-22-años">a. ¿Cuál es la probabilidad de que, en promedio, la intensidad de la música escuchada por los encuestados menores a 18 años supere en 10 decibeles a la intensidad de la música escuchada por los encuestados mayores a 22 años?</h4>
<p><span class="math display">\[
\mathbb{P}(\overline{X}_1 - \overline{X}_2 &gt; 10) = 1 - \mathbb{P}(\overline{X}_1 - \overline{X}_2 \leq 10) = 1 - \mathbb{P}\left(T(v) \leq \frac{10 - (\mu_1 - \mu_2)}{\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}}\right)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>((x<span class="sc">-</span>m)<span class="sc">/</span>s,v, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.746964e-44</code></pre>
</div>
</div>
</section>
<section id="b.-con-95-de-confianza-cuál-es-el-intervalo-de-confianza-para-la-diferencia-de-medias" class="level4">
<h4 class="anchored" data-anchor-id="b.-con-95-de-confianza-cuál-es-el-intervalo-de-confianza-para-la-diferencia-de-medias">b. Con 95% de confianza, ¿cuál es el intervalo de confianza para la diferencia de medias?</h4>
<p>El intervalo de confianza se calcula con la fórmula:</p>
<p><span class="math display">\[
\mathbb{P}\left(\overline{X}_1 - \overline{X}_2 - t_{(1-\alpha/2,v)} \cdot \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}} \leq \mu_1 - \mu_2 \leq \overline{X}_1 - \overline{X}_2 + t_{(1-\alpha/2,v)} \cdot \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}\right) = 0.95
\]</span></p>
<p>El intervalo de confianza es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>ic <span class="ot">&lt;-</span> m <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span>t<span class="sc">*</span>s</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"El intervalo de confianza para la varianza poblacional es ["</span>, ic[<span class="dv">1</span>], <span class="st">";"</span>, ic[<span class="dv">2</span>], <span class="st">"] con un nivel de confianza del 95%."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El intervalo de confianza para la varianza poblacional es [ 0.296085048979667 ; 1.99345592114914 ] con un nivel de confianza del 95%."</code></pre>
</div>
</div>
<p>Otra forma de calcularlo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(df1<span class="sc">$</span>average_loudness, df2<span class="sc">$</span>average_loudness, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">var.equal =</span> <span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  df1$average_loudness and df2$average_loudness
t = 2.6678, df = 134.1, p-value = 0.008575
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 0.296091 1.993450
sample estimates:
mean of x mean of y 
-6.434169 -7.578939 </code></pre>
</div>
</div>
<p>¿Cómo se ve la distribución de la diferencia de medias?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>Xs <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">7</span>, <span class="dv">7</span>, <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Xs, <span class="fu">dt</span>(Xs,v), <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">c</span>(ic[<span class="dv">1</span>], ic[<span class="dv">2</span>]), <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(Xs[Xs <span class="sc">&gt;</span> t], <span class="fu">dt</span>(Xs[Xs <span class="sc">&gt;</span> t],v), <span class="at">col =</span> <span class="st">"green"</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"T(x,v)"</span>, <span class="st">"respuesta de la a."</span>, <span class="st">"respuesta de la b."</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>,<span class="st">"green"</span>, <span class="st">"blue"</span>), <span class="at">lty =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="proyecto-spotify_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="caso-de-estudio-4" class="level1">
<h1>Caso de estudio #4</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">runs.test</span>(DF<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Runs Test

data:  DF$age
statistic = 0.81701, runs = 105, n1 = 82, n2 = 123, n = 205, p-value =
0.4139
alternative hypothesis: nonrandomness</code></pre>
</div>
</div>
<section id="caso-de-estudio-5-regresión-lineal-múltiple" class="level2">
<h2 class="anchored" data-anchor-id="caso-de-estudio-5-regresión-lineal-múltiple">Caso de estudio 5 (Regresión Lineal Múltiple)</h2>
<p>Ahora analizaremos si es útil el modelo de regresión múltiple para predecir la edad de una persona a partir de las variables <strong>danceability</strong>, <strong>energy</strong> y <strong>acousticness</strong>.</p>
<p>Agrupo los datos en un data frame para hacer mejor el análisis de regresión múltiple y realizamos el modelo de regresión múltiple.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>df_caso_5 <span class="ot">&lt;-</span> DF <span class="sc">%&gt;%</span> <span class="fu">select</span>(age, average_danceability, average_energy, average_acousticness)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>regression <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> average_danceability <span class="sc">+</span> average_energy <span class="sc">+</span> average_acousticness, <span class="at">data =</span> df_caso_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para empezar a visualizar cómo se relacionan, graficamos un heatmap de correlación.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(df_caso_5[,<span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"average_danceability"</span>, <span class="st">"average_energy"</span>, <span class="st">"average_acousticness"</span>)])</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>melted_cor_matrix <span class="ot">&lt;-</span> <span class="fu">melt</span>(cor_matrix)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(melted_cor_matrix, <span class="fu">aes</span>(<span class="at">x=</span>Var1, <span class="at">y=</span>Var2, <span class="at">fill=</span>value)) <span class="sc">+</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="at">low=</span><span class="st">"blue"</span>, <span class="at">high=</span><span class="st">"red"</span>, <span class="at">mid=</span><span class="st">"white"</span>, </span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">midpoint=</span><span class="dv">0</span>, <span class="at">limit=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="at">space=</span><span class="st">"Lab"</span>, </span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">name=</span><span class="st">"Correlación"</span>) <span class="sc">+</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">45</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">""</span>, <span class="at">y=</span><span class="st">""</span>, <span class="at">title=</span><span class="st">"Heatmap de correlación"</span>) <span class="sc">+</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">round</span>(value, <span class="dv">2</span>)), <span class="at">size=</span><span class="dv">4</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="proyecto-spotify_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A priori, no parece haber una correlación fuerte entre las variables, por lo que el modelo de regresión múltiple podría ser útil.</p>
<p>Extraemos los coeficientes de la regresión múltiple para graficar las rectas de regresión simple.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>b_0 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">coef</span>(regression)[<span class="st">"(Intercept)"</span>])</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">coef</span>(regression)[<span class="st">"average_danceability"</span>])</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>b_2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">coef</span>(regression)[<span class="st">"average_energy"</span>])</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>b_3 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">coef</span>(regression)[<span class="st">"average_acousticness"</span>])</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>b_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.446895</code></pre>
</div>
</div>
<p>Graficamos las rectas de regresión múltiple y las comparamos con las rectas de regresión simple.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_caso_5<span class="sc">$</span>average_danceability, df_caso_5<span class="sc">$</span>age)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(b_0, b_1, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(df_caso_5<span class="sc">$</span>age <span class="sc">~</span> df_caso_5<span class="sc">$</span>average_danceability), <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_caso_5<span class="sc">$</span>average_energy, df_caso_5<span class="sc">$</span>age)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(b_0, b_2, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(df_caso_5<span class="sc">$</span>age <span class="sc">~</span> df_caso_5<span class="sc">$</span>average_energy), <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span>(<span class="st">"Regresión múltiple"</span>)</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_caso_5<span class="sc">$</span>average_acousticness, df_caso_5<span class="sc">$</span>age)</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(b_0, b_3, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(df_caso_5<span class="sc">$</span>age <span class="sc">~</span> df_caso_5<span class="sc">$</span>average_acousticness), <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">"Regresión múltiple"</span>, <span class="st">"Regresión simple"</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>), <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">cex=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="proyecto-spotify_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>De manera individual, las rectas son diferentes, pero en general siguen la misma tendencia. Para ver la utilidad del modelo de regresión múltiple, analizamos los errores usando la independencia, la normalidad y la homocedasticidad.</p>
<section id="analizamos-los-errores" class="level3">
<h3 class="anchored" data-anchor-id="analizamos-los-errores">Analizamos los errores</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>errores <span class="ot">&lt;-</span> regression<span class="sc">$</span>residuals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="test-de-independencia" class="level4">
<h4 class="anchored" data-anchor-id="test-de-independencia">Test de independencia</h4>
<p><span class="math display">\[
\mathsf{\text{Test de Durwin Watson}} \\
Ho: \text{Los errores son independientes} \\
Ha: \text{Los errores no son independientes}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>dw <span class="ot">&lt;-</span> <span class="fu">dwtest</span>(regression,<span class="at">alternative =</span><span class="st">"two.sided"</span>,<span class="at">iterations =</span> <span class="dv">1000</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>dw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  regression
DW = 1.9338, p-value = 0.5989
alternative hypothesis: true autocorrelation is not 0</code></pre>
</div>
</div>
<p>El <strong>p-value</strong> es 0.5989418, que es mayor que 0.05, además DW está entre 1.5 y 2.5, por lo que fallamos en rechazar la hipótesis nula. Los errores son independientes.</p>
</section>
<section id="test-de-normalidad" class="level4">
<h4 class="anchored" data-anchor-id="test-de-normalidad">Test de normalidad</h4>
<p><span class="math display">\[
\mathsf{\text{Test de Kolmogorov Smirnov}}\\
Ho: \text{Los errores tienen distribución normal, con media cero}\\
Ha: \text{Los errores no tienen distribución normal, con media cero}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>ks <span class="ot">&lt;-</span> <span class="fu">ks.test</span>(errores, <span class="st">"pnorm"</span>, <span class="fu">mean</span>(errores), <span class="fu">sd</span>(errores))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>ks</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  errores
D = 0.068073, p-value = 0.1796
alternative hypothesis: two-sided</code></pre>
</div>
</div>
<p>El <strong>p-value</strong> es 0.1795687, que es mayor que 0.05, por lo que fallamos en rechazar la hipótesis nula. Los errores tienen distribución normal, con media cero.</p>
</section>
<section id="test-de-homocedasticidad" class="level4">
<h4 class="anchored" data-anchor-id="test-de-homocedasticidad">Test de homocedasticidad</h4>
<p><span class="math display">\[
\mathsf{\text{Test de Breusch Pagan}} \\
Ho: \text{Los errores tienen varianza constante (homocedasticidad)} \\
Ha: \text{Los errores no tienen varianza constante (heterocedasticidad)}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">bptest</span>(regression)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>bp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  regression
BP = 2.3464, df = 3, p-value = 0.5037</code></pre>
</div>
</div>
<p>El <strong>p-value</strong> es 0.5036919, que es mayor que 0.05, por lo que fallamos en rechazar la hipótesis nula. Los errores tienen varianza constante (homocedasticidad).</p>
</section>
<section id="conclusión-de-análisis-de-errores" class="level4">
<h4 class="anchored" data-anchor-id="conclusión-de-análisis-de-errores">Conclusión de análisis de errores</h4>
<p>Los errores son independientes, tienen distribución normal y varianza constante, por lo que el modelo de regresión múltiple es útil para predecir la edad de una persona a partir de las variables <strong>danceability</strong>, <strong>energy</strong> y <strong>acousticness</strong>.</p>
</section>
</section>
<section id="prueba-de-hipótesis-en-la-regresión-múltiple" class="level3">
<h3 class="anchored" data-anchor-id="prueba-de-hipótesis-en-la-regresión-múltiple">Prueba de hipótesis en la regresión múltiple</h3>
<p>Ahora probaremos la significancia de los coeficientes de la regresión múltiple. La ecuación es:</p>
<p><span class="math display">\[
\text{age} = \beta_0 + \beta_1 \times \text{danceability} + \beta_2 \times \text{energy} + \beta_3 \times \text{acousticness}
\]</span></p>
<section id="prueba-de-significancia-de-los-coeficientes" class="level4">
<h4 class="anchored" data-anchor-id="prueba-de-significancia-de-los-coeficientes">Prueba de significancia de los coeficientes</h4>
<p>Probaremos si <span class="math inline">\(\beta_0, \beta_1, \beta_2, \beta_3\)</span> son significativamente diferentes de cero. Para esto nos basta con ver el <strong>p-value</strong> de cada coeficiente en el modelo que nos da R.</p>
<p><span class="math display">\[\mathsf{\text{Test de significancia de coeficientes}} \]</span> <span class="math display">\[Ho: \beta_0 = 0 \qquad \beta_1 = 0 \qquad \beta_2 = 0 \qquad \beta_3 = 0 \]</span> <span class="math display">\[Ha: \beta_0 \neq 0 \qquad \beta_1 \neq 0 \qquad \beta_2 \neq 0 \qquad \beta_3 \neq 0\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ average_danceability + average_energy + average_acousticness, 
    data = df_caso_5)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.7364 -1.3168 -0.0947  0.9775  6.3149 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           23.1728     0.8823  26.265  &lt; 2e-16 ***
average_danceability  -2.7044     0.8765  -3.085 0.002255 ** 
average_energy        -2.7005     0.7961  -3.392 0.000803 ***
average_acousticness   1.4469     0.6426   2.252 0.025184 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.969 on 256 degrees of freedom
Multiple R-squared:  0.1412,    Adjusted R-squared:  0.1311 
F-statistic: 14.03 on 3 and 256 DF,  p-value: 1.709e-08</code></pre>
</div>
</div>
<p>Observamos que los <strong>p-value</strong> de los coeficientes <span class="math inline">\(\beta_0, \beta_1, \beta_2, \beta_3\)</span> son todos menores que 0.05, por lo que rechazamos la hipótesis nula y concluimos que los coeficientes son significativamente diferentes de cero.</p>
</section>
<section id="prueba-de-significancia-del-modelo" class="level4">
<h4 class="anchored" data-anchor-id="prueba-de-significancia-del-modelo">Prueba de significancia del modelo</h4>
<p><span class="math display">\[\mathsf{\text{Test de significancia del modelo}} \]</span> <span class="math display">\[Ho: \text{El modelo no es significativo} \]</span> <span class="math display">\[Ha: \text{El modelo es significativo}\]</span></p>
<p>Vemos también que el <strong>p-value</strong> del modelo es menor que 0.05, por lo que rechazamos la hipótesis nula y concluimos que el modelo es significativamente diferente de cero.</p>
</section>
</section>
<section id="conclusión-de-caso-de-estudio-5" class="level3">
<h3 class="anchored" data-anchor-id="conclusión-de-caso-de-estudio-5">Conclusión de Caso de estudio 5</h3>
<p>Determinamos que nuestro modelo de regresión múltiple es útil para predecir la edad de una persona a partir de las variables <strong>danceability</strong>, <strong>energy</strong> y <strong>acousticness</strong>. Además, concluimos que todas las variables son significativas para predecir la edad de una persona.</p>
<p>Un ejemplo de la aplicación de esto es: Si tenemos la canción <em>Blinding Lights</em> de The Weeknd, con <strong>danceability</strong> 0.514, <strong>energy</strong> 0.73 y <strong>acousticness</strong> 0.001, entonces la edad de la persona que escucha esta canción es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(b_0 <span class="sc">+</span> b_1 <span class="sc">*</span> <span class="fl">0.514</span> <span class="sc">+</span> b_2 <span class="sc">*</span> <span class="fl">0.73</span> <span class="sc">+</span> b_3 <span class="sc">*</span> <span class="fl">0.001</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20</code></pre>
</div>
</div>
</section>
</section>
<section id="caso-de-estudio-6-regresión-lineal-simple" class="level2">
<h2 class="anchored" data-anchor-id="caso-de-estudio-6-regresión-lineal-simple">Caso de estudio 6 (Regresión Lineal Simple)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">select</span>(DF, listened_artists, age)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>regression2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(df2<span class="sc">$</span>listened_artists <span class="sc">~</span> df2<span class="sc">$</span>age)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>regression2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = df2$listened_artists ~ df2$age)

Coefficients:
(Intercept)      df2$age  
    952.339        3.928  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df2<span class="sc">$</span>age, df2<span class="sc">$</span>listened_artists)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(df2<span class="sc">$</span>listened_artists <span class="sc">~</span> df2<span class="sc">$</span>age), <span class="at">col=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="proyecto-spotify_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Podemos observar que a medida que las personas se hacen mayores, la cantidad de artistas que escuchan al año, no parece variar mucho.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = df2$listened_artists ~ df2$age)

Residuals:
    Min      1Q  Median      3Q     Max 
-1025.8  -634.4  -112.0   497.0  3062.2 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  952.339    425.023   2.241   0.0259 *
df2$age        3.928     21.386   0.184   0.8544  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 726.9 on 258 degrees of freedom
Multiple R-squared:  0.0001307, Adjusted R-squared:  -0.003745 
F-statistic: 0.03373 on 1 and 258 DF,  p-value: 0.8544</code></pre>
</div>
</div>
<p>El <strong>p-value</strong> del coeficiente de la edad, del intercepto y del modelo son mayores que 0.05, por lo que fallamos en rechazar la hipótesis nula.</p>
<section id="conclusión-de-caso-de-estudio-6-regresión-lineal-simple" class="level3">
<h3 class="anchored" data-anchor-id="conclusión-de-caso-de-estudio-6-regresión-lineal-simple">Conclusión de Caso de estudio 6 (Regresión Lineal Simple)</h3>
<p>Concluimos que el modelo de regresión simple no es útil para predecir la cantidad de artistas anuales que se escuchan a partir de la edad. No podemos decir que la edad influye en la cantidad de artistas anuales que se escuchan.</p>
<p>Si a pesar de esto, se insistiera en usar el modelo, se puede decir que: una persona de 20 años escucha en promedio 1031 artistas al año.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(<span class="fu">round</span>(regression2<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> regression2<span class="sc">$</span>coefficients[<span class="dv">2</span>] <span class="sc">*</span> <span class="dv">20</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1031</code></pre>
</div>
</div>
</section>
</section>
<section id="caso-de-estudio-7-diseño-de-experimentos" class="level2">
<h2 class="anchored" data-anchor-id="caso-de-estudio-7-diseño-de-experimentos">Caso de estudio 7 (Diseño de experimentos)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>df_caso_5 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>age) <span class="sc">%&gt;%</span> <span class="fu">stack</span>() <span class="ot">-&gt;</span> sdf3</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>an_sdf3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(values <span class="sc">~</span> ind, <span class="at">data =</span> sdf3)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(an_sdf3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
ind           2  43.47  21.737   618.4 &lt;2e-16 ***
Residuals   777  27.31   0.035                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<table class="table">
<colgroup>
<col style="width: 21%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>FUENTE</th>
<th>GL</th>
<th>SC</th>
<th>CM</th>
<th>FO</th>
<th>P VALOR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TRATAMIENTOS</td>
<td>k-1=2</td>
<td>SCTr=43.47</td>
<td>CMTr=21.737</td>
<td>Fo=618.4</td>
<td>P=2e-161</td>
</tr>
<tr class="even">
<td>ERROR</td>
<td>N-k=777</td>
<td>SCE=27.31</td>
<td>CME=0.035</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>TOTAL</td>
<td>N-1=779</td>
<td>SCT=70.78</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(<span class="fl">618.4</span>, <span class="dv">2</span>, <span class="dv">777</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.080746e-161</code></pre>
</div>
</div>
<p>El <strong>p-value</strong> es 0.998002, que es muchisimo menor que 0.05, por lo que rechazamos la hipótesis nula. Concluimos que hay diferencias significativas entre las variables <strong>danceability</strong>, <strong>energy</strong> y <strong>acousticness</strong>. Debido al <strong>p-value</strong>, que es pequeño, no hay ninguna duda de que hay diferencias significativas.</p>
<p>Para analizar mejor las diferencias, realizamos un test de Tukey.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(an_sdf3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = values ~ ind, data = sdf3)

$ind
                                                 diff          lwr         upr
average_energy-average_danceability        0.02869231 -0.009919605  0.06730422
average_acousticness-average_danceability -0.48584930 -0.524461211 -0.44723739
average_acousticness-average_energy       -0.51454161 -0.553153519 -0.47592969
                                              p adj
average_energy-average_danceability       0.1892364
average_acousticness-average_danceability 0.0000000
average_acousticness-average_energy       0.0000000</code></pre>
</div>
</div>
<p>-0.0099 &lt; energy-danceability &lt; 0.0673 -0.5245 &lt; acousticness-danceability &lt; -0.4472 -0.5532 &lt; acousticness-energy &lt; -0.4759</p>
<p>energy = danceability acousticness &lt; danceability acousticness &lt; energy</p>
<p>El órden más apropiado es <strong>acousticness</strong> &lt; <strong>danceability</strong> = <strong>energy</strong></p>
<section id="conclusión-de-caso-de-estudio-7" class="level3">
<h3 class="anchored" data-anchor-id="conclusión-de-caso-de-estudio-7">Conclusión de Caso de estudio 7</h3>
<p>Concluimos que en spotify son más escuchadas las canciones con mayor danceability y energy, con un acousticness más bajo.</p>
<p>Es decir, canciones como: <em>Blinding Lights</em> de The Weeknd, con <strong>danceability</strong> 0.514, <strong>energy</strong> 0.73 y <strong>acousticness</strong> 0.001, son más escuchadas que canciones como: <em>The Night We Met</em> de Lord Huron, con <strong>danceability</strong> 0.351, <strong>energy</strong> 0.405 y <strong>acousticness</strong> 0.86.</p>
</section>
</section>
<section id="caso-de-estudio-8-experimento-de-percepción-de-géneros" class="level2">
<h2 class="anchored" data-anchor-id="caso-de-estudio-8-experimento-de-percepción-de-géneros">Caso de estudio 8: experimento de percepción de géneros</h2>
<p>En este experimento vamos a comparar como es que el genero percibido como favorito de las personas se relaciona con el volumen e intensidad de sus canciones escuchadas. En un estudio reciente se hablo de la “Guerra del volumen” y como es que existe una correlación entre popularidad de una cancion y su intensidad promedio. Nosotros vamos a utilizar la correlación entre intensidad y genero para responder a las siguientes preguntas:</p>
<ul>
<li><p>Que genero es el que tiene mayor energía promedio?</p></li>
<li><p>Que genero es el que tiene mayor volumen promedio?</p></li>
<li><p>Que tan acertada es la percepción de las personas sobre su genero favorito? Para este ultimo vamos a extraer la intencidad promedio de los generos más populares del siguiente <a href="https://github.com/isaackwy/loudness-wars-spotify">estudio</a></p></li>
</ul>
<p>Los generos que seran considerados en este estudio son los siguientes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>rock <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">loudness =</span> <span class="sc">-</span><span class="fl">8.169173438842325</span>,</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">energy =</span> <span class="fl">0.7070176326516859</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>r_and_b <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">loudness =</span> <span class="sc">-</span><span class="fl">7.8536782465833515</span>,</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">energy =</span> <span class="fl">0.5891415262417352</span></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>pop <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">loudness =</span> <span class="sc">-</span><span class="fl">6.962477605529706</span>,</span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">energy =</span> <span class="fl">0.6268352900526923</span></span>
<span id="cb83-12"><a href="#cb83-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-13"><a href="#cb83-13" aria-hidden="true" tabindex="-1"></a>edm <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb83-14"><a href="#cb83-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">loudness =</span> <span class="sc">-</span><span class="fl">6.239374065852863</span>,</span>
<span id="cb83-15"><a href="#cb83-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">energy =</span> <span class="fl">0.783228764081047</span></span>
<span id="cb83-16"><a href="#cb83-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-17"><a href="#cb83-17" aria-hidden="true" tabindex="-1"></a>latin <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb83-18"><a href="#cb83-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">loudness =</span> <span class="sc">-</span><span class="fl">7.167930645280326</span>,</span>
<span id="cb83-19"><a href="#cb83-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">energy =</span> <span class="fl">0.6853391368991688</span></span>
<span id="cb83-20"><a href="#cb83-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-21"><a href="#cb83-21" aria-hidden="true" tabindex="-1"></a>rap <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb83-22"><a href="#cb83-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">loudness =</span> <span class="sc">-</span><span class="fl">7.402685040690765</span>,</span>
<span id="cb83-23"><a href="#cb83-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">energy =</span> <span class="fl">0.6688384486114174</span></span>
<span id="cb83-24"><a href="#cb83-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-25"><a href="#cb83-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-26"><a href="#cb83-26" aria-hidden="true" tabindex="-1"></a>average_genres_info <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb83-27"><a href="#cb83-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> <span class="fu">c</span>(<span class="st">"rock"</span>, <span class="st">"r&amp;b"</span>, <span class="st">"pop"</span>, <span class="st">"edm"</span>, <span class="st">"latin"</span>, <span class="st">"rap"</span>),</span>
<span id="cb83-28"><a href="#cb83-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">loudness =</span> <span class="fu">c</span>(rock<span class="sc">$</span>loudness, r_and_b<span class="sc">$</span>loudness, pop<span class="sc">$</span>loudness, edm<span class="sc">$</span>loudness, latin<span class="sc">$</span>loudness, rap<span class="sc">$</span>loudness),</span>
<span id="cb83-29"><a href="#cb83-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">energy =</span> <span class="fu">c</span>(rock<span class="sc">$</span>energy, r_and_b<span class="sc">$</span>energy, pop<span class="sc">$</span>energy, edm<span class="sc">$</span>energy, latin<span class="sc">$</span>energy, rap<span class="sc">$</span>energy)</span>
<span id="cb83-30"><a href="#cb83-30" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="table">
<thead>
<tr class="header">
<th>name</th>
<th>loudness</th>
<th>energy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rock</td>
<td>-8.1691734</td>
<td>0.7070176</td>
</tr>
<tr class="even">
<td>R&amp;B</td>
<td>-7.8536782</td>
<td>0.5891415</td>
</tr>
<tr class="odd">
<td>Pop</td>
<td>-6.9624776</td>
<td>0.6268353</td>
</tr>
<tr class="even">
<td>EDM</td>
<td>-6.2393741</td>
<td>0.7832288</td>
</tr>
<tr class="odd">
<td>Latin</td>
<td>-7.1679306</td>
<td>0.6853391</td>
</tr>
<tr class="even">
<td>Rap</td>
<td>-7.402685</td>
<td>0.6688384</td>
</tr>
</tbody>
</table>
<p>Aqui podemos observar que, en promedio, el genero con mayor enería y volumen es el EDM, seguido por el Rock, vamos a ver si esto concuerda con la data que tenemos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># group by genre</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="co"># do the same for the other genres  </span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>users_genre_data <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">rock =</span> <span class="fu">filter</span>(DF, favourite_gender <span class="sc">==</span> <span class="st">"rock"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(average_loudness, average_energy),</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">r_and_b =</span> <span class="fu">filter</span>(DF, favourite_gender <span class="sc">==</span> <span class="st">"r&amp;b"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(average_loudness, average_energy),</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pop =</span> <span class="fu">filter</span>(DF, favourite_gender <span class="sc">==</span> <span class="st">"pop"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(average_loudness, average_energy),</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">edm =</span> <span class="fu">filter</span>(DF, favourite_gender <span class="sc">==</span> <span class="st">"edm"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(average_loudness, average_energy),</span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">latin =</span> <span class="fu">filter</span>(DF, favourite_gender <span class="sc">==</span> <span class="st">"latin"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(average_loudness, average_energy),</span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">rap =</span> <span class="fu">filter</span>(DF, favourite_gender <span class="sc">==</span> <span class="st">"rap"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(average_loudness, average_energy)</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a>biggest_genre_count <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">sapply</span>(users_genre_data, nrow))</span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-14"><a href="#cb84-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the missing data with NA</span></span>
<span id="cb84-15"><a href="#cb84-15" aria-hidden="true" tabindex="-1"></a>users_genre_data <span class="ot">&lt;-</span> <span class="fu">lapply</span>(users_genre_data, <span class="cf">function</span>(x) {</span>
<span id="cb84-16"><a href="#cb84-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(x) <span class="sc">&lt;</span> biggest_genre_count) {</span>
<span id="cb84-17"><a href="#cb84-17" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">&lt;-</span> <span class="fu">rbind</span>(x, <span class="fu">data.frame</span>(<span class="at">average_loudness =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, biggest_genre_count <span class="sc">-</span> <span class="fu">nrow</span>(x)), <span class="at">average_energy =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, biggest_genre_count <span class="sc">-</span> <span class="fu">nrow</span>(x))))</span>
<span id="cb84-18"><a href="#cb84-18" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb84-19"><a href="#cb84-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(x)</span>
<span id="cb84-20"><a href="#cb84-20" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb84-21"><a href="#cb84-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-22"><a href="#cb84-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-23"><a href="#cb84-23" aria-hidden="true" tabindex="-1"></a><span class="co">#combine all loudness data by genre</span></span>
<span id="cb84-24"><a href="#cb84-24" aria-hidden="true" tabindex="-1"></a>users_loudness_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb84-25"><a href="#cb84-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">genre =</span> <span class="fu">rep</span>(<span class="fu">names</span>(users_genre_data), <span class="at">each =</span> biggest_genre_count),</span>
<span id="cb84-26"><a href="#cb84-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">loudness =</span> <span class="fu">unlist</span>(<span class="fu">lapply</span>(users_genre_data, <span class="cf">function</span>(x) x<span class="sc">$</span>average_loudness))</span>
<span id="cb84-27"><a href="#cb84-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb84-28"><a href="#cb84-28" aria-hidden="true" tabindex="-1"></a>users_energy_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb84-29"><a href="#cb84-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">genre =</span> <span class="fu">rep</span>(<span class="fu">names</span>(users_genre_data), <span class="at">each =</span> biggest_genre_count),</span>
<span id="cb84-30"><a href="#cb84-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">energy =</span> <span class="fu">unlist</span>(<span class="fu">lapply</span>(users_genre_data, <span class="cf">function</span>(x) x<span class="sc">$</span>average_energy))</span>
<span id="cb84-31"><a href="#cb84-31" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb84-32"><a href="#cb84-32" aria-hidden="true" tabindex="-1"></a>loudnes_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(loudness<span class="sc">~</span>genre, <span class="at">data=</span>users_loudness_data)</span>
<span id="cb84-33"><a href="#cb84-33" aria-hidden="true" tabindex="-1"></a>energy_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(energy<span class="sc">~</span>genre, <span class="at">data=</span>users_energy_data)</span>
<span id="cb84-34"><a href="#cb84-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-35"><a href="#cb84-35" aria-hidden="true" tabindex="-1"></a>loudness_aov_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(loudnes_aov)</span>
<span id="cb84-36"><a href="#cb84-36" aria-hidden="true" tabindex="-1"></a>energy_aov_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(energy_aov)</span>
<span id="cb84-37"><a href="#cb84-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-38"><a href="#cb84-38" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(users_loudness_data<span class="sc">$</span>genre))</span>
<span id="cb84-39"><a href="#cb84-39" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(users_loudness_data)</span>
<span id="cb84-40"><a href="#cb84-40" aria-hidden="true" tabindex="-1"></a>loudness_aov_data <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb84-41"><a href="#cb84-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCTr =</span> loudness_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Sum Sq"</span>]][<span class="dv">1</span>],</span>
<span id="cb84-42"><a href="#cb84-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCE =</span> loudness_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Sum Sq"</span>]][<span class="dv">2</span>],</span>
<span id="cb84-43"><a href="#cb84-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCT =</span> loudness_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Sum Sq"</span>]][<span class="dv">1</span>] <span class="sc">+</span> loudness_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Sum Sq"</span>]][<span class="dv">2</span>],</span>
<span id="cb84-44"><a href="#cb84-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">CMTr =</span> loudness_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Mean Sq"</span>]][<span class="dv">1</span>],</span>
<span id="cb84-45"><a href="#cb84-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">CME =</span> loudness_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Mean Sq"</span>]][<span class="dv">2</span>],</span>
<span id="cb84-46"><a href="#cb84-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">f_value =</span> loudness_aov_summary[[<span class="dv">1</span>]][[<span class="st">"F value"</span>]],</span>
<span id="cb84-47"><a href="#cb84-47" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> loudness_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Pr(&gt;F)"</span>]][<span class="dv">1</span>]</span>
<span id="cb84-48"><a href="#cb84-48" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb84-49"><a href="#cb84-49" aria-hidden="true" tabindex="-1"></a>energy_aov_data <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb84-50"><a href="#cb84-50" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCTr =</span> energy_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Sum Sq"</span>]][<span class="dv">1</span>],</span>
<span id="cb84-51"><a href="#cb84-51" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCE =</span> energy_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Sum Sq"</span>]][<span class="dv">2</span>],</span>
<span id="cb84-52"><a href="#cb84-52" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCT =</span> energy_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Sum Sq"</span>]][<span class="dv">1</span>] <span class="sc">+</span> energy_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Sum Sq"</span>]][<span class="dv">2</span>],</span>
<span id="cb84-53"><a href="#cb84-53" aria-hidden="true" tabindex="-1"></a>  <span class="at">CMTr =</span> energy_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Mean Sq"</span>]][<span class="dv">1</span>],</span>
<span id="cb84-54"><a href="#cb84-54" aria-hidden="true" tabindex="-1"></a>  <span class="at">CME =</span> energy_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Mean Sq"</span>]][<span class="dv">2</span>],</span>
<span id="cb84-55"><a href="#cb84-55" aria-hidden="true" tabindex="-1"></a>  <span class="at">f_value =</span> energy_aov_summary[[<span class="dv">1</span>]][[<span class="st">"F value"</span>]],</span>
<span id="cb84-56"><a href="#cb84-56" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> energy_aov_summary[[<span class="dv">1</span>]][[<span class="st">"Pr(&gt;F)"</span>]][<span class="dv">1</span>]</span>
<span id="cb84-57"><a href="#cb84-57" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb84-58"><a href="#cb84-58" aria-hidden="true" tabindex="-1"></a>energy_aov_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$SCTr
[1] 0.8059577

$SCE
[1] 7.979322

$SCT
[1] 8.78528

$CMTr
[1] 0.1611915

$CME
[1] 0.03141465

$f_value
[1] 5.131094       NA

$p_value
[1] 0.0001676276</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>loudness_aov_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$SCTr
[1] 279.5373

$SCE
[1] 2115.576

$SCT
[1] 2395.113

$CMTr
[1] 55.90746

$CME
[1] 8.329039

$f_value
[1] 6.712354       NA

$p_value
[1] 6.792929e-06</code></pre>
</div>
</div>
<p>AOV loudness</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>FUENTE</th>
<th>GL</th>
<th>SC</th>
<th>CM</th>
<th>FO</th>
<th>P VALOR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TRATAMIENTOS</td>
<td>5</td>
<td>279.5372859</td>
<td>55.9074572</td>
<td>6.7123541, NA</td>
<td>6.7929288^{-6}</td>
</tr>
<tr class="even">
<td>ERROR</td>
<td>336</td>
<td>2115.5758295</td>
<td>8.3290387</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>TOTAL</td>
<td>341</td>
<td>2395.1131154</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>AOV energy</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>FUENTE</th>
<th>GL</th>
<th>SC</th>
<th>CM</th>
<th>FO</th>
<th>P VALOR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TRATAMIENTOS</td>
<td>5</td>
<td>0.8059577</td>
<td>0.1611915</td>
<td>5.1310937, NA</td>
<td>1.6762761^{-4}</td>
</tr>
<tr class="even">
<td>ERROR</td>
<td>336</td>
<td>7.9793223</td>
<td>0.0314147</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>TOTAL</td>
<td>341</td>
<td>8.78528</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>H0 : <span class="math inline">\(\mu_1 = \mu_2 = \mu_3\)</span><br>
Ha: <span class="math inline">\(\exists i \neq j\)</span> tal que <span class="math inline">\(\mu_i \neq \mu_j\)</span></p>
<p>Dado que los <strong>p-value</strong> son 6.7929288^{-6} y 1.6762761^{-4}, ambos menores que 0.05, rechazamos la hipótesis nula. Concluimos que hay diferencias significativas entre los generos en cuanto a la intensidad y volumen de las canciones escuchadas. Sin embargo, las diferencias de loudness son significativamente menores que las diferencias de energía, esto se debe a que estan en una escala logaritmica y tambien debido a que estamos estudiando generos modernos, los cuales, segun la fuente original, tienen un loudness promedio muy alto y similar. En caso de haber estudiado generos como el jazz o la música clásica, las diferencias de loudness hubieran sido más significativas.</p>
<p>Ahora vamos a calcular que genero es el que tiene mayor energía promedio y que genero es el que tiene mayor volumen promedio segun la data de los usuarios.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>highest_loudness_genre <span class="ot">&lt;-</span> users_loudness_data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean_loudness =</span> <span class="fu">mean</span>(loudness)) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_loudness)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">1</span>)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>highest_energy_genre <span class="ot">&lt;-</span> users_energy_data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean_energy =</span> <span class="fu">mean</span>(energy)) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_energy)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">1</span>)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>highest_loudness_genre</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  genre mean_loudness
  &lt;chr&gt;         &lt;dbl&gt;
1 pop           -6.29</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>highest_energy_genre</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  genre mean_energy
  &lt;chr&gt;       &lt;dbl&gt;
1 pop         0.701</code></pre>
</div>
</div>
<p>Dado que observamos que las diferencias de loudness son significativamente menores que las diferencias de energía, vamos a analizar si es que esta sigue una distribución normal con una prueba de Kolmogorov Smirnov.</p>
<p><span class="math inline">\(H_0\)</span>: Los datos siguen una distribución normal<br>
<span class="math inline">\(H_a\)</span>: Los datos no siguen una distribución normal</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>users_average_loudness_data <span class="ot">&lt;-</span> DF<span class="sc">$</span>average_loudness</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>ks_p_value <span class="ot">&lt;-</span> <span class="fu">ks.test</span>(users_average_loudness_data, <span class="st">"pnorm"</span>, <span class="fu">mean</span>(users_average_loudness_data), <span class="fu">sd</span>(users_average_loudness_data))<span class="sc">$</span>p.value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in ks.test.default(users_average_loudness_data, "pnorm",
mean(users_average_loudness_data), : ties should not be present for the
Kolmogorov-Smirnov test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>ks_p_value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003660792</code></pre>
</div>
</div>
<p>Dado que el <strong>p-value</strong> es 0.0036608, que es menor que 0.05, rechazamos la hipótesis nula. Concluimos que los datos no siguen una distribución normal.</p>
<p>En la prueba de Kolmogorov Smirnov realizada existieron valores repetidos, por lo que para confirmar este resultado vamos a realizar una prueba de Anderson-Darling para verificar si los datos siguen una distribución normal y la acompañaremos con un histograma.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(users_average_loudness_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  users_average_loudness_data
A = 4.6709, p-value = 1.332e-11</code></pre>
</div>
</div>
<p>Nuevamente, el <strong>p-value</strong> es menor que 0.05, por lo que rechazamos la hipótesis nula. Concluimos que los datos no siguen una distribución normal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co">#loudness_norm_vec &lt;- rnorm(260, mean(users_average_loudness_data), sd(users_average_loudness_data))</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="co">#plotNormalHistogram(data_vector, prob = FALSE, main = "Normal Distribution overlay on Histogram", length = 1000)</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming your data is stored in a vector named 'data_vector'</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>mean_value <span class="ot">&lt;-</span> <span class="fu">mean</span>(users_average_loudness_data) <span class="co"># Replace with your mean value</span></span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>sd_value <span class="ot">&lt;-</span> <span class="fu">sd</span>(users_average_loudness_data) <span class="co"># Replace with your SD value</span></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a sequence of x values for plotting</span></span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a>x_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(users_average_loudness_data), <span class="fu">max</span>(users_average_loudness_data), <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb98-10"><a href="#cb98-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-11"><a href="#cb98-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the ggplot object</span></span>
<span id="cb98-12"><a href="#cb98-12" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> users_average_loudness_data), <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb98-13"><a href="#cb98-13" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">binwidth =</span> <span class="fu">diff</span>(<span class="fu">range</span>(users_average_loudness_data))<span class="sc">/</span><span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"lightgray"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb98-14"><a href="#cb98-14" aria-hidden="true" tabindex="-1"></a> <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> mean_value, <span class="at">sd =</span> sd_value), <span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb98-15"><a href="#cb98-15" aria-hidden="true" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Normal Distribution vs. Actual Data"</span>, <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span>
<span id="cb98-16"><a href="#cb98-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-17"><a href="#cb98-17" aria-hidden="true" tabindex="-1"></a><span class="co">#dnorm(mean_value, )</span></span>
<span id="cb98-18"><a href="#cb98-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-19"><a href="#cb98-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the actual data as a histogram</span></span>
<span id="cb98-20"><a href="#cb98-20" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> users_average_loudness_data), <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb98-21"><a href="#cb98-21" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">binwidth =</span> <span class="fu">diff</span>(<span class="fu">range</span>(users_average_loudness_data))<span class="sc">/</span><span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"lightgray"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb98-22"><a href="#cb98-22" aria-hidden="true" tabindex="-1"></a> <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> mean_value, <span class="at">sd =</span> sd_value), <span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb98-23"><a href="#cb98-23" aria-hidden="true" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Normal Distribution vs. Actual Data"</span>, <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span>
<span id="cb98-24"><a href="#cb98-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb98-25"><a href="#cb98-25" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="proyecto-spotify_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A continuación, vamos a mapear un género para cada usuario segun el volumen promedio de las canciones que escuchan. Luego, vamos a comparar el género mapeado con el género percibido como favorito por el usuario. Para darle a cada usuario un genero estimado, vamos a asignarle aquel que tenga el volumen promedio más cercano al volumen promedio de las canciones que escucha segun la variable <code>average_genders_info</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>average_genres_loudness <span class="ot">&lt;-</span> average_genres_info <span class="sc">%&gt;%</span> <span class="fu">select</span>(name, loudness)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="co"># filter loudness &amp; favourite_gender</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>users_estimated_genre <span class="ot">&lt;-</span> DF <span class="sc">%&gt;%</span> <span class="fu">select</span>(average_loudness, favourite_gender)</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a><span class="co"># We will add a new column to the dataframe with the estimated genre</span></span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>users_estimated_genre<span class="sc">$</span>estimated_genre <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a>users_estimated_genre<span class="sc">$</span>estimated_genre <span class="ot">&lt;-</span> <span class="fu">sapply</span>(users_estimated_genre<span class="sc">$</span>average_loudness, <span class="cf">function</span>(x) {</span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a>  genre <span class="ot">&lt;-</span> average_genres_loudness<span class="sc">$</span>name[<span class="fu">which.min</span>(<span class="fu">abs</span>(average_genres_loudness<span class="sc">$</span>loudness <span class="sc">-</span> x))]</span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(genre)</span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb99-11"><a href="#cb99-11" aria-hidden="true" tabindex="-1"></a>users_estimated_genre</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 260 × 3
   average_loudness favourite_gender estimated_genre
              &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;          
 1           -10.1  rock             rock           
 2            -4.74 rock             edm            
 3            -7.50 r&amp;b              rap            
 4            -5.82 r&amp;b              edm            
 5            -1.99 pop              edm            
 6            -6.16 r&amp;b              edm            
 7           -10.0  r&amp;b              rock           
 8            -6.35 r&amp;b              edm            
 9            -4.89 edm              edm            
10            -6.06 r&amp;b              edm            
# ℹ 250 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we will add a new column to the dataframe with 0 if the favourite is the same as the estimated, 1 if it is different</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>users_estimated_genre<span class="sc">$</span>correct <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(users_estimated_genre<span class="sc">$</span>favourite_gender <span class="sc">==</span> users_estimated_genre<span class="sc">$</span>estimated_genre, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we will calculate the percentage of correct estimations</span></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>correct_estimations <span class="ot">&lt;-</span> <span class="fu">sum</span>(users_estimated_genre<span class="sc">$</span>correct <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">nrow</span>(users_estimated_genre) <span class="sc">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>El porcentaje de aciertos es 20.7692308, lo que significa que la percepción de las personas sobre su genero favorito es acertada en un 20% de los casos.</p>
</section>
<section id="caso-de-estudio-9" class="level2">
<h2 class="anchored" data-anchor-id="caso-de-estudio-9">Caso de estudio 9</h2>
<p>En este caso de estudio vamos a analizar la relación entre el la corrección de la percepción de género y la cantidad de canciones escuchadas por año. Para esto vamos a realizar un test de independencia entre estas dos variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(DF<span class="sc">$</span>listened_artists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    5.0   394.5   917.5  1030.0  1523.0  4097.0 </code></pre>
</div>
</div>
<p>En primer lugar, vamos a categorizar la cantidad de canciones escuchadas por año en 4 categorias: muy baja, baja, media, alta y muy alta.</p>
<table class="table">
<thead>
<tr class="header">
<th>Categoría</th>
<th>Cantidad de canciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Muy baja</td>
<td>0 - 100</td>
</tr>
<tr class="even">
<td>Baja</td>
<td>100 - 500</td>
</tr>
<tr class="odd">
<td>Media</td>
<td>500 - 1500</td>
</tr>
<tr class="even">
<td>Alta</td>
<td>1500 - 3000</td>
</tr>
<tr class="odd">
<td>Muy alta</td>
<td>3000 - 5000</td>
</tr>
</tbody>
</table>
</section>
<section id="referenicas-bibliográficas" class="level2">
<h2 class="anchored" data-anchor-id="referenicas-bibliográficas">Referenicas bibliográficas</h2>
<ul>
<li>Hujran, O., Alikaj, A., Durrani, U., &amp; Al-Dmour, N. A. (2020). Big Data and its Effect on the Music Industry. ACM. https://doi.org/10.1145/3378936.3378957</li>
<li>Álvarez, P., De Quirós, J. G., &amp; Baldassarri, S. (2023). RIADA: a Machine-Learning based infrastructure for recognising the emotions of Spotify songs. International Journal of Interactive Multimedia and Artificial Intelligence, 8(2), 168. https://doi.org/10.9781/ijimai.2022.04.002</li>
<li>Spotify for Developers. (18 de enero de 2024). https://developer.spotify.com/</li>
<li>Isaac Yu. loudness-wars-spotify. retrieved from https://github.com/isaackwy/loudness-wars-spotify</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>